### ISSUE TITLE
Lezioni: Update json structure with new "urlInfo"

### ISSUE THREAD

**Issue by Deco71** [appinfosapienza/UniBotJS#20]
I'll leave it up to you my beloved <3

**Comment by dag7dev** [comment]
Why is urlInfo required? What's this new field?

**Comment by Deco71** [comment]
See #18, it's not a big issue, but separating the two things imo Is prettier. For example, with this new entity you can create a /announcements command and show all the info for all the courses (like , the fact

**Comment by Deco71** [comment]
See #18, it's not a big issue, but separating the two things imo Is prettier. For example, with this new entity you can create a /announcements command and show all the info for all the courses (like the fact that the SO2 lessons start the 3rd of March)

**Comment by dag7dev** [comment]
I've proceeded in this way because I was just merging plaintext files into JSON and Discord parses link without additional work.

So we need two separate fields, urlLezione and urlInfo, is it correct?

**Comment by Deco71** [comment]
Yep

Il ven 25 feb 2022, 18:33 Dag7 ***@***.***> ha scritto:
